### ISSUE TITLE
Remove unbounded loops

### ISSUE THREAD

**Issue by chriseth** [ConsenSys/MultiSigWallet#1]
The contract contains several potentially unbounded loops regarding the number of owners. While such a wallet should usually not have many owners, I think it would be better to add a look-up data structure that removes the necessity for such loops. Furthermore, removing an owner is currently a very costly operation.

**Comment by Georgi87** [comment]
Thank you for reporting this issue. I fixed it in 0c61c07f8be912b6117d25e94baf2f1dcbf36a5a Please have a look.

**Comment by Georgi87** [comment]
Please check this commit too: 4592ef140eb8c6498d4a9099852ed65d8b267f4d

This commit prevents overwriting confirmations.

**Comment by chriseth** [comment]
Now it is not possible to get a list of all owners... :-)

**Comment by Georgi87** [comment]
Simple to add it again :)

How would you implement the `removeOwner` function to remove the owner from the ownership array?
Iterate over the list until we find the owner, replace him with the last one and reduce array size by 1?

**Comment by Georgi87** [comment]
Loop for removing an owner and loop for counting confirmations were improved.

I favor keeping the loop for counting owner confirmations instead of keeping track of confirmations as part of the transaction object to not count confirmations by removed owners.

**Comment by chriseth** [comment]
I think the current loops are fine, but perhaps there should be a hard limit on the number of owners? It is probably better to make adding an owner fail than having the wallet stuck completely.

**Comment by chriseth** [comment]
How much gas does it cost?

**Comment by Georgi87** [comment]
Gas costs to create a wallet with 50 owners is 330.000 gas.
Gas costs to remove the last owner in an array with 50 is 90.000 gas.

Added a constraint for 50 max and a test 5d74295c48d2b8ec0d6e6be7731b288ed235792b

I cannot imagine anyone will ever need 50 owners.

**Comment by ethers** [comment]
It seems `transactionHashes` is/can be unbounded ?

**Comment by Georgi87** [comment]
It is only used for web3 function calls. Transactions only add to the array with constant costs.
