### ISSUE TITLE
All owners can be removed

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#18]
For the record, edge case appears that there's no tests for removing the last owner: all owners can be removed by wallet repeatedly invoking `removeOwner`.

**Comment by Georgi87** [comment]
No, not all owners can be removed. See issue https://github.com/ConsenSys/MultiSigWallet/issues/2

**Comment by ethers** [comment]
Thanks, I see `removeOwner` calls `validRequirement` indirectly by `updateRequirement`....  The test case mentioned in #2 (assert failure) would still have been good to add.

**Comment by Georgi87** [comment]
Added a test for it: cb477371e95d0261d3266cd725c3622443a1522f
