### ISSUE TITLE
Add protection against too few owners

### ISSUE THREAD

**Issue by chriseth** [ConsenSys/MultiSigWallet#2]
It should never be possible to have zero owners (not even in the constructor) or a required field that is larger than the number of owners.

**Comment by Georgi87** [comment]
Thanks for this one too. It's fixed in 0c61c07f8be912b6117d25e94baf2f1dcbf36a5a Please check.

**Comment by chriseth** [comment]
It is still possible to get the number of owners to zero.

**Comment by Georgi87** [comment]
Not really, `checkRequired` will throw in case `ownerCount == 0`. And `removeOwner` will always trigger `checkRequired` in case `required > ownerCount`.

**Comment by Georgi87** [comment]
fixed in 0c61c07f8be912b6117d25e94baf2f1dcbf36a5a

**Comment by chriseth** [comment]
It is still possible to remove all owners, I think that should be prevented.

**Comment by Georgi87** [comment]
I tried to create a test scenario to check if I can remove all owner, but it doesn't work/tx fails. Sorry but I must be missing something. This is the code to remove an owner:

```
    modifier validRequirement(uint _ownerCount, uint _required) {
        if (   _required > _ownerCount
            || _required == 0
            || _ownerCount == 0)
            throw;
        _;
    }

    function removeOwner(address owner)
        external
        onlyWallet
        ownerExists(owner)
    {
        isOwner[owner] = false;
        for (uint i=0; i<owners.length - 1; i++)
            if (owners[i] == owner) {
                owners[i] = owners[owners.length - 1];
                break;
            }
        owners.length -= 1;
        if (required > owners.length)
            updateRequirement(owners.length);
        OwnerRemoval(owner);
    }

    function updateRequirement(uint _required)
        public
        onlyWallet
        validRequirement(owners.length, _required)
    {
        required = _required;
        RequirementUpdate(_required);
    }
```

Assuming we have one owner and `required` is 1. If we want to remove this last owner with `removeOwner`, `updateRequirement` is executed. `updateRequirement` has the modifier `validRequirement`, which will throw if owner count is 0. So in this case this modifier will throw.

In what scenario could we remove all owners?

**Comment by chriseth** [comment]
Oh I'm sorry. Thanks for the detailed explanation, I did not see the call to `validRequirement()`.
