### ISSUE TITLE
Make returns consistent

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#22]
For safety and clarity, prefer explicit returns. And remove unused named returns.  See #21

**Comment by Georgi87** [comment]
They are all consistent. Return statements are used as part of the control flow in case a function has to return before the end of the function block. Named return parameters are used for natspec comments.

**Comment by Georgi87** [comment]
Another reason to not use explicit return statements if not necessary is that it needs one position less on the stack if we just set the variable named in the function signature and don't initialize another one.

Anyways I agree that we can remove namings for return variables that are not used.

E.g.
```
    /// @dev Returns transaction hashes of pending transactions.
    /// @return _transactionList List of transaction hashes.
    function getPendingTransactions()
        public
        constant
        returns (bytes32[] _transactionList)
    {
        return filterTransactions(true);
    }
```

To
```
    /// @dev Returns transaction hashes of pending transactions.
    /// @return List of transaction hashes.
    function getPendingTransactions()
        public
        constant
        returns (bytes32[])
    {
        return filterTransactions(true);
    }
```

**Comment by ethers** [comment]
> Return statements are used as part of the control flow in case a function has to return before the end of the function block.

Yes, that's a good case, but the the wallet code doesn't require it.

Natspec appears to be a project that is shelved, whereas this code is likely to be looked upon as an example.  Named return parameters are not a familiar feature in other programming languages, they can be misused accidentally (example https://github.com/ethereum/solidity/issues/718#issue-165439717), and they are not as clear from a safety perspective than being explicit and returning values in the way that most programmer would be familiar with.

Yes, there is some gas saving, but safety should come first, in most contracts, and moreso a wallet.

(Anecdotally, when TheDao happened these named return parameters were a feature that some said shows that Solidity wasn't a good design for security.  I tend to agree, and if there are further plans to to tie them with something like Natspec, we should consider how it can be done in a way that keeps code clear and minimizes accidental misuse.  Named returns that are unused, like this example https://github.com/ConsenSys/MultiSigWallet/issues/22#issuecomment-261532509, suggest that the idea could possibly be improved.)

Should I update the title to something like "avoid named returns"?

**Comment by Georgi87** [comment]
>Natspec appears to be a project that is shelved
Is it really? I think the development around this is done on solc side and it is a good way to give some basic understanding how the code functions.

>Yes, there is some gas saving, but safety should come first, in most contracts, and moreso a wallet.
It has the same safety. Understanding the code requires knowledge in Solidity but this is OK.  And as the stack in solidity is very limited, reusing memory allocated for return values is a good practice IMO.

>Should I update the title to something like "avoid named returns"?
Unused named return statements should be removed but I would still suggest to use them, if possible.

**Comment by ethers** [comment]
I think `isConfirmed` should explicitly `return false` after the loop.

Started a discussion about named returns at https://github.com/ethereum/solidity/issues/1401 with examples of how it can cause confusion.  At this stage, imo smart contracts should strive for clarity, explicitness, safety _over_ relying on technicalities, scoping rules, language familiarity...

**Comment by Georgi87** [comment]
In my opinion named returns are quite useful because of limited stack size. Gas costs are an issue too, but the limit in stack size is even more problematic. Think of a function, which has multiple returns. Would you like to initialize a new variable for each of them? Stack size is very low code has to be efficient.

I agree with you that it is easier for non-solidity programmers to understand code w/o named returns and explicit returns, but I would also not recommend someone to write Python like C, because it is easier to understand for a C programmer.

I will follow the discussion you started. This code will be updated with future solidity changes. If named returns are removed from solidity, they will be removed from our code too. For now I will close this ticket.
