### ISSUE TITLE
dailylimit test coverage

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#24]
```
        if (now > lastDay + 24 hours) {
            lastDay = now;
            spentToday = 0;
        }
        if (spentToday + amount > dailyLimit)
            return false;
        spentToday += amount;
        return true;
```
https://github.com/ConsenSys/MultiSigWallet/blob/master/contracts/solidity/MultiSigWalletWithDailyLimit.sol#L64-L71
There are 4 code paths and the test only covers 3 of them: a missing test  is when both `if` evaluate to true (a spend over the dailylimit after 1 day).

It would also be nice to have boundary tests eg:
* now == lastDay + 24 hours
* spentToday + amount == dailyLimit
* spentToday + amount == dailyLimit + 1

More minor is:
* now == lastDay + 24 hours - 1
* spentToday + amount == dailyLimit 1 1

**Comment by Georgi87** [comment]
I agree a test for the fourth path would be good to have. I will add it.

Testing basic arithmetic functions seem like overkill for me.

**Comment by Georgi87** [comment]
> There are 4 code paths and the test only covers 3 of them: a missing test is when both if evaluate to true (a spend over the dailylimit after 1 day).

added in 62443211056c49c85ca0e8b3c8b04978a8433b58
