### ISSUE TITLE
No test when executeTransaction throws

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#27]
https://github.com/ConsenSys/MultiSigWallet/blob/master/contracts/solidity/MultiSigWalletWithDailyLimit.sol#L48-L49

```
            if (!tx.destination.call.value(tx.value)(tx.data))
                throw;
```

**Comment by Georgi87** [comment]
There is a test for this already: https://github.com/ConsenSys/MultiSigWallet/blob/dapp/contracts/tests/test_owner_add_limit.py#L58

I think you wrote this test :)
