### ISSUE TITLE
No reverse lookup of transactionHash

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#28]
Given a transactionHash, it may be difficult to find these values: (address destination, uint value, bytes data, uint nonce)
For example, if a transactionHash isn't working as expected due to a typo in destination, value, or data, it might be difficult to find out what and where the typo was.
"isn't working as expected" in this case means that `tx.destination.call.value(tx.value)(tx.data)` does return true, but because say the destination is wrong, that the transaction isn't getting executed on the correct contract.

**Comment by Georgi87** [comment]
I think this is a UI task. With the function `transaction(tx_hash)` you get the values of the submitted transaction.

**Comment by ethers** [comment]
Right, `transactions(tx_hash)`.
