### ISSUE TITLE
There should be a way to get the list of all active transactions

### ISSUE THREAD

**Issue by chriseth** [ConsenSys/MultiSigWallet#3]
For the user interface, it is much more reliable to get the list of all transactions from a constant function call instead of scanning for events. This might also be helpful for past transactions.

**Comment by Georgi87** [comment]
Added in 6867fb93de1af35e951edff42ce0a6d02e01e841

`getPendingTransactions`
`getExecutedTransactions`

**Comment by chriseth** [comment]
Nice!
