### ISSUE TITLE
destination zero assumptions

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#30]
`notNull(destination)` and https://github.com/ConsenSys/MultiSigWallet/blob/dapp/contracts/solidity/MultiSigWallet.sol#L288 make assumptions about destination 0.

This is more for discussion/brainstorm.

Could there be any cases currently or in the future where sending a transaction to the zero address could be valid and useful?  I guess the syntax `tx.destination.call...` means the zero address can never be used.

Should the check perhaps be changed to use the nonce?  Like this:
```
        if (transactions[transactionHash].nonce == 0) {  // use nonce instead
            transactions[transactionHash] = Transaction({
                destination: destination,
                value: value,
                data: data,
                nonce: nonce++,  // increment here just as nonces below is += 1 ?
                executed: false
            });
            nonces[keccak256(destination, value, data)] += 1;
```

**Comment by Georgi87** [comment]
The only reason to do a tx with destination 0 would be the creation of contracts. This version of the wallet will not support the creation of contracts via a proxy contract.  This is why the destination address cannot be null and can be used to check for an existing transaction.

**Comment by ethers** [comment]
> We should name this limitation in the readme.
Agree.

I think using a destination of 0 would cause an immediate error in Solidity, so it wouldn't work even if it was allowed.  But it's helpful for us to consider any other assumptions that the code makes.

**Comment by Georgi87** [comment]
Added it to the readme: c285eae696ab09c639a292f128a9cdb0d516c20d
