### ISSUE TITLE
submitTransaction relies on transitive modifiers

### ISSUE THREAD

**Issue by ethers** [ConsenSys/MultiSigWallet#34]
`submitTransaction` has no modifiers so it looks callable by anyone.  Except one of the functions it calls has an `ownerExists` modifier.  It would be clearer for this to be upfront (even though `submitTransaction` is only 2 lines of code).

**Comment by Georgi87** [comment]
I agree it would be a little clearer but result in the duplicate unnecessary application of modifiers. I will not change this.
