### ISSUE TITLE
Cosmetic Bug : TestToken.sol -- `totalSupply` uint256 not increased under issuance

### ISSUE THREAD

**Issue by SilentCicero** [ConsenSys/MultiSigWallet#36]
Totally cosmetic, but you forgot to increase totalSupply with your MultiSig test token. I think it shows good due diligence to the public when all vars stated are used properly, even if they are cosmetic markers.

Code lines here:
https://github.com/ConsenSys/MultiSigWallet/blob/master/contracts/solidity/TestToken.sol#L12-L18

I would recommend you either remove `totalSupply` or use it.

Anyway, just a thought.

**Comment by Georgi87** [comment]
Thanks for checking! Added in 3831b631665dc3391109759f53d5421f27b3b883
