### ISSUE TITLE
Add a way to use pre-signed confirmations

### ISSUE THREAD

**Issue by chriseth** [ConsenSys/MultiSigWallet#4]
For efficiency reasons, it would make sense to provide a method where multiple signatures can be provided in a single call (i.e. signatures not from msg.sender). At best, this could result in a multisig transaction being executed within a single transaction.

**Comment by Georgi87** [comment]
Added in 7a3af5aff80b365f5eb2f1e3d9f1ba2a357a4391

**Comment by Georgi87** [comment]
And refactored as an inheriting contract in dcf528d557542122bca762cb0a7cbf385b7d1dcc
