### ISSUE TITLE
addOwner/removeOwner Transaction

### ISSUE THREAD

**Issue by luandt-cardano** [ConsenSys/MultiSigWallet#48]
These transactions are called if using only wallet. It means that MultiSigwallet contract call function addOwner or removeOwner by itself. How can it work?
Thanks

**Comment by luandt-cardano** [comment]
The way they work as sending ETH to another address. I understood the work flow.

**Comment by denisgranha** [comment]
you need to use https://github.com/ConsenSys/MultiSigWallet/blob/master/contracts/solidity/MultiSigWallet.sol#L169
and in data use the data used by addOwner function
