### ISSUE TITLE
Specify behaviour concerning owner change

### ISSUE THREAD

**Issue by chriseth** [ConsenSys/MultiSigWallet#5]
It is not immediately obvious what will happen to pending transactions during an owner change.

**Comment by Georgi87** [comment]
The current implementation will count confirmations of removed owners. The previous one did not count them but required a list of owners. It seems better to me to not count confirmations of removed owners. Should we undo this change?

**Comment by chriseth** [comment]
I think confirmations of removed owners should be removed together with the owners.
