### ISSUE TITLE
Add MultiSigWallet to EPM

### ISSUE THREAD

**Issue by skmgoldin** [ConsenSys/MultiSigWallet#52]
Problem: the MultiSigWallet is not available on EPM.

Steps to reproduce:
1. Go to https://www.ethpm.com/registry/packages
2. Look for the MultiSigWallet
3. Dismay at the absence of the MultiSigWallet

Proposed solution: publish the MultiSigWallet to EPM.

**Comment by Georgi87** [comment]
Uploaded for ropsten testnet: https://www.ethpm.com/registry/packages/14

**Comment by skmgoldin** [comment]
YOU'RE THE BEST
