### ISSUE TITLE
It's not deploying my wallet

### ISSUE THREAD

**Issue by awsashish** [ConsenSys/MultiSigWallet#53]
I am adding my poloniex ETH wallet on given live site url and also on deployed code, I have filled all information but when I clicked on “Deploy” then nothing happen there… It is neither saving any information nor showing any error.

Please help me.

**Comment by denisgranha** [comment]
Hello @awsashish, could you explain a bit more your situation?

What do you mean by adding you poloniex wallet?

First of all you must access https://wallet.gnosis.pm with a 3rd party wallet: https://metamask.io/ or https://github.com/ethereum/mist
At the main page, if it's the first time you access the page you should click on add > Create new Wallet.

In the Deploy view you just need to add the name you want to assign to the wallet and by default will take your ethereum account as default owner, you can add other owners before deploying.
