### ISSUE TITLE
Error when creating new MultiSigWallet from Factory

### ISSUE THREAD

**Issue by flyswatter** [ConsenSys/MultiSigWallet#55]
I tried to create a multisig wallet from factory, set the initial settings, it asked for a metamask approval, and I hit approve, it said "Deployment was sent to factory contract",

but then the list of wallets did not update.

I opened the inspector, and it threw an error:

```
Uncaught TypeError: Cannot read property 'events' of undefined
    at Object.callback [as 0x76751a278e147a49ed07d2b490171ba01dfe6e57fc4a9155cd7db9ffa1e28e11] 
```

I looked at where this error was thrown, and it was a line that said this:
```javascript
callback: function(receipt){
                    var walletAddress = receipt.decodedLogs[0].events[1].value;
```

This might also be Ropsten lag.  I know Ropsten is doing awful, and this was on Ropsten.

**Comment by denisgranha** [comment]
Thanks for your report @flyswatter we have noticed that in Ropsten the factory contract is not triggering logs, we will look into this in detail

**Comment by denisgranha** [comment]
this was a ropsten issue, working fine now
