### ISSUE TITLE
test errors

### ISSUE THREAD

**Issue by zynis** [ConsenSys/MultiSigWallet#62]
first, I wanted to mention that the install documentation is missing some steps like

vagrant ssh

however once I am in, I get this - any idea what's up?

vagrant@vagrant-ubuntu-trusty-64:/vagrant/contracts$ python -m unittest tests.test_multisig_wallet

/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum/_solidity.py:319: UserWarning: solc_wrapper is deprecated, please use the functions compile_file or compile_code
  warnings.warn('solc_wrapper is deprecated, please use the functions compile_file or compile_code')
E
======================================================================
ERROR: test (tests.test_multisig_wallet.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_multisig_wallet.py", line 39, in test
    constructor_parameters=constructor_parameters)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum/tester.py", line 215, in abi_contract
    contract_interface = compiler.mk_full_signature(sourcecode, path=path, **kwargs)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum/_solidity.py", line 350, in mk_full_signature
    result = cls._code_or_path(code, path, contract_name, libraries, 'abi', extra_args)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum/_solidity.py", line 337, in _code_or_path
    result = compile_code(sourcecode, libraries=libraries, combined=combined, extra_args=extra_args)
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ethereum/_solidity.py", line 305, in compile_code
    raise CompileError(stderrdata)
CompileError: <stdin>:1:1: Error: Source file requires different compiler version (current compiler is 0.4.10+commit.59099908.Linux.g++ - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.4;
^--------------------^

----------------------------------------------------------------------
Ran 1 test in 0.027s

FAILED (errors=1)

**Comment by denisgranha** [comment]
solc version of apt-get is not mantained, so everytime the solc compiler is updated by the foundation they break a lot of code.
The code is intented to be run with 0.4.4
You cannot get that version from
https://launchpad.net/~ethereum/+archive/ubuntu/ethereum

**Comment by zynis** [comment]
Actually we found that this works without vagrant just by going into the
dapp folder and following the web GUI instructions... the instructions
really needs to be updated
