### ISSUE TITLE
`calcMaxWithdraw` can overflow when daily limit is exceeded

### ISSUE THREAD

**Issue by yaronvel** [ConsenSys/MultiSigWallet#80]
It is possible to exceed daily limit simply by having enough confirmations for a tx.
In this case `calcMaxWithdraw` can return negative number.
Since result is `uint`, it is presented as very high positive number.

**Comment by cag** [comment]
I believe there is a check which prevents underflow in that function.

**Comment by yaronvel** [comment]
right, sorry.

**Comment by cag** [comment]
No worries! Always good to have more eyes on the code.
